### PR TITLE
Revert "Selecting index view manually"

### PR DESCRIPTION
**Pull request by nmolkeri**
Reverts christianhelle/ScrollableSegmentedControl#20

### CODE REVIEW

**Comment by nmolkeri** [comment]
@christianhelle can you update license to this project?

**Comment by christianhelle** [comment]
@nmolkeri I have never given the license for this project any thought. What will work best for you?

**Comment by nmolkeri** [comment]
MIT would be good if that's not an issue.

**Comment by christianhelle** [comment]
@nmolkeri Done

**Comment by nmolkeri** [comment]
Thank you very much. :)

**Pull request merged**
